name: Delete Branch
on:
  delete:
    branches:
      - '**' 

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: remove s3 key
        run: |
          aws s3 rm s3://$BUCKET/${{ github.event.ref }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
          BUCKET: asgard-main-bucket

